{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-diagrammer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DiagrammeR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DiagrammeR/DiagrammeR_{{ version }}.tar.gz
  sha256: 0877af707925b03c58a7e00cd84eb4e9906b551a61d86130ef4165477654e334

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer >=1.1_2
    - r-downloader >=0.4
    - r-dplyr >=0.7.4
    - r-glue >=1.2.0
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=1.0
    - r-igraph >=1.1.2
    - r-influencer >=0.1.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.4
    - r-readr >=1.1.1
    - r-rgexf >=0.15.3
    - r-rlang >=0.2.0
    - r-rstudioapi >=0.7
    - r-scales >=0.5.0
    - r-stringr >=1.3.0
    - r-tibble >=1.4.2
    - r-tidyr >=0.8.0
    - r-viridis >=0.5.0
    - r-visnetwork >=2.0.3
  run:
    - r-base
    - r-rcolorbrewer >=1.1_2
    - r-downloader >=0.4
    - r-dplyr >=0.7.4
    - r-glue >=1.2.0
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=1.0
    - r-igraph >=1.1.2
    - r-influencer >=0.1.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.4
    - r-readr >=1.1.1
    - r-rgexf >=0.15.3
    - r-rlang >=0.2.0
    - r-rstudioapi >=0.7
    - r-scales >=0.5.0
    - r-stringr >=1.3.0
    - r-tibble >=1.4.2
    - r-tidyr >=0.8.0
    - r-viridis >=0.5.0
    - r-visnetwork >=2.0.3

test:
  commands:
    - $R -e "library('DiagrammeR')"           # [not win]
    - "\"%R%\" -e \"library('DiagrammeR')\""  # [win]

about:
  home: https://github.com/rich-iannone/DiagrammeR
  license: MIT
  license_file: LICENSE
  summary: ' Build graph/network structures using functions for stepwise addition and deletion
    of nodes and edges. Work with data available in tables for bulk addition of nodes,
    edges, and associated metadata. Use graph selections and traversals to apply changes
    to specific nodes or edges. A wide selection of graph algorithms allow for the analysis
    of graphs. Visualize the graphs and take advantage of any aesthetic properties assigned
    to nodes and edges.'
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: DiagrammeR
# Title: Graph/Network Visualization
# Version: 1.0.1
# Authors@R: person("Richard", "Iannone", email = "riannone@me.com", role = c("aut", "cre"))
# Maintainer: Richard Iannone <riannone@me.com>
# Description:  Build graph/network structures using functions for stepwise addition and deletion of nodes and edges. Work with data available in tables for bulk addition of nodes, edges, and associated metadata. Use graph selections and traversals to apply changes to specific nodes or edges. A wide selection of graph algorithms allow for the analysis of graphs. Visualize the graphs and take advantage of any aesthetic properties assigned to nodes and edges.
# Depends: R (>= 3.2.0)
# License: MIT + file LICENSE
# Imports: dplyr (>= 0.7.4), downloader (>= 0.4), glue (>= 1.2.0), htmltools (>= 0.3.6), htmlwidgets (>= 1.0), igraph (>= 1.1.2), influenceR (>= 0.1.0), magrittr (>= 1.5), purrr (>= 0.2.4), RColorBrewer (>= 1.1-2), readr (>= 1.1.1), rlang (>= 0.2.0), rstudioapi (>= 0.7), rgexf (>= 0.15.3), scales (>= 0.5.0), stringr (>= 1.3.0), tibble (>= 1.4.2), tidyr (>= 0.8.0), viridis (>= 0.5.0), visNetwork (>= 2.0.3)
# Suggests: covr, DiagrammeRsvg, rsvg, knitr, testthat
# URL: https://github.com/rich-iannone/DiagrammeR
# BugReports: https://github.com/rich-iannone/DiagrammeR/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2019-04-21 07:44:49 UTC; ripley
# Author: Richard Iannone [aut, cre]
# Repository: CRAN
# Date/Publication: 2019-04-22 06:53:42 UTC
