{% set version = "1.0.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-diagrammer
  version: {{ version|replace("-", "_") }}

source:
  fn: DiagrammeR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/DiagrammeR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/DiagrammeR/DiagrammeR_{{ version }}.tar.gz
  sha256: 2b186dae1b19018681b979e9444bf16559c42740d8382676fbaf3b0f8a44337e

build:
  number: 0
  # r-igraph is not available for Windows
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dplyr >=0.5.0
    - r-downloader >=0.4
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=1.0
    - r-igraph >=1.1.2
    - r-influencer >=0.1.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.3
    - r-rcolorbrewer >=1.1_2
    - r-readr >=1.1.1
    - r-rlang >=0.1.1
    - r-rstudioapi >=0.6
    - r-rgexf >=0.15.3
    - r-scales >=0.5.0
    - r-stringr >=1.2.0
    - r-tibble >=1.3.3
    - r-tidyr >=0.6.3
    - r-viridis >=0.4.0
    - r-visnetwork >=2.0.1
  run:
    - r-base
    - r-dplyr >=0.5.0
    - r-downloader >=0.4
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=1.0
    - r-igraph >=1.1.2
    - r-influencer >=0.1.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.3
    - r-rcolorbrewer >=1.1_2
    - r-readr >=1.1.1
    - r-rlang >=0.1.1
    - r-rstudioapi >=0.6
    - r-rgexf >=0.15.3
    - r-scales >=0.5.0
    - r-stringr >=1.2.0
    - r-tibble >=1.3.3
    - r-tidyr >=0.6.3
    - r-viridis >=0.4.0
    - r-visnetwork >=2.0.1

test:
  commands:
    - $R -e "library('DiagrammeR')"  # [not win]
    - "\"%R%\" -e \"library('DiagrammeR')\""  # [win]

about:
  home: https://github.com/rich-iannone/DiagrammeR
  license: MIT
  summary: Create graph diagrams and flowcharts using R.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
